site:
  title: "Image Gallery"
  theme: default
  themePicker: enabled

# list of themes
# --------------
#
# default: the green-mocha default theme
# simple: a simple black and white theme
# bubblegum: a blue and pink theme
